package com.osheaven.bushcraft;

import com.osheaven.bushcraft.proxy.CommonProxy;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import static com.osheaven.bushcraft.Reference.*;

@Mod(
        modid = MODID,
        name = MODNAME,
        version = VERSION,
        acceptedMinecraftVersions = ACCEPTED,
        dependencies = DEPENDENCIES
)
public class Bushcraft
{
    @SidedProxy(
            clientSide = "com.osheaven.bushcraft.proxy.ClientProxy",
            serverSide = "com.osheaven.bushcraft.proxy.CommonProxy"
    )
    public static CommonProxy proxy;

    @Instance(value=MODID)
    public static Bushcraft instance;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        ModMetadata data = event.getModMetadata();
        data.autogenerated  = false;
        data.version = VERSION;
        data.modId = MODID;
        data.name = MODNAME;
        data.description = DESCRIPTION;
        data.credits = CREDITS;
        data.url = URL;
        data.logoFile = LOGOFILE;
        data.authorList.add(AUTHOR);

        proxy.preInit(event);
    }

    @EventHandler
    public void init(FMLInitializationEvent e)
    {
        proxy.init(e);
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent e)
    {
        proxy.postInit(e);
    }
}
